"""Remove unique constraint from award_date

Revision ID: af6d12bb6685
Revises: 86bdb190e1a2
Create Date: 2025-07-01 03:21:57.405080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6d12bb6685'
down_revision: Union[str, None] = '86bdb190e1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('awards_award_date_key', 'awards', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('awards_award_date_key', 'awards', ['award_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
